name: Deploy to Google Cloud Run

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GAR_LOCATION: asia-northeast3
    SERVICE: ppfdbe
    REPOSITORY: ppfdbe

jobs:
    deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Google Auth
              id: auth
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

            - name: Set up Cloud SDK
              uses: "google-github-actions/setup-gcloud@v1"

            - name: Configure Docker
              run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

            - name: Build and Push Container
              run: |-
                  IMAGE_TAG=$(echo "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
                  docker build -t ${IMAGE_TAG} .
                  docker push ${IMAGE_TAG}

            - name: Deploy to Cloud Run
              id: deploy
              run: |-
                  IMAGE_TAG=$(echo "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
                  gcloud run deploy ${{ env.SERVICE }} \
                    --image ${IMAGE_TAG} \
                    --platform managed \
                    --region ${{ env.GAR_LOCATION }} \
                    --allow-unauthenticated