name: Deploy to Google Cloud Run

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GAR_LOCATION: asia-northeast3
    SERVICE: ppfdbe
    REPOSITORY: ppfdbe
    # Optional repo variables (Settings -> Variables) for non-secret config
    DB_NAME: ${{ vars.DB_NAME }}
    APP_ENV: ${{ vars.ENV }}

jobs:
    deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Google Auth
              id: auth
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

            - name: Set up Cloud SDK
              uses: "google-github-actions/setup-gcloud@v1"

            - name: Configure Docker
              run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

            - name: Ensure Secret Manager has MONGODB_URI and grant access
              run: |-
                  set -euo pipefail
                  # Create secret if it doesn't exist, then always add a new version
                  echo -n "${{ secrets.MONGODB_URI }}" | gcloud secrets create MONGODB_URI \
                    --project "${{ env.PROJECT_ID }}" \
                    --replication-policy=automatic \
                    --data-file=- \
                  || echo "Secret MONGODB_URI already exists"
                  echo -n "${{ secrets.MONGODB_URI }}" | gcloud secrets versions add MONGODB_URI \
                    --project "${{ env.PROJECT_ID }}" \
                    --data-file=-
                  # Grant the default compute service account access to the secret
                  PROJECT_NUMBER=$(gcloud projects describe "${{ env.PROJECT_ID }}" --format='value(projectNumber)')
                  SA_EMAIL="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
                  gcloud projects add-iam-policy-binding "${{ env.PROJECT_ID }}" \
                    --member "serviceAccount:${SA_EMAIL}" \
                    --role roles/secretmanager.secretAccessor \
                    --quiet

            - name: Build and Push Container
              run: |-
                  IMAGE_TAG=$(echo "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
                  docker build -t ${IMAGE_TAG} .
                  docker push ${IMAGE_TAG}

            - name: Deploy to Cloud Run
              id: deploy
              run: |-
                  IMAGE_TAG=$(echo "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
                  gcloud run deploy ${{ env.SERVICE }} \
                    --image ${IMAGE_TAG} \
                    --platform managed \
                    --region ${{ env.GAR_LOCATION }} \
                    --allow-unauthenticated \
                    --set-secrets MONGODB_URI=MONGODB_URI:latest \
                    --set-env-vars DB_NAME=${DB_NAME:-PPFDDB},ENV=${APP_ENV:-production}
